name: Keyline
favicon: null
layout_spectrum: 0.2853748840279877
typography_spectrum: 0.39905759040266275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#98cfeb'
    - '#ffffff'
    - '#236f94'
    - '#565656'
  brandStrength: 0.9112770222127438
  lightness: 0.3104355994146317
  saturation: 0.20994145818986
  rhythmicContrast: 0.1308886562474072
purpose: []
